# Generated by Django 5.0.2 on 2024-02-21 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_address_users_district_users_region_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='blogs')),
                ('title', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.RenameField(
            model_name='products',
            old_name='photo',
            new_name='photo1',
        ),
        migrations.AddField(
            model_name='products',
            name='photo2',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='photo3',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='photo4',
            field=models.ImageField(blank=True, null=True, upload_to='products'),
        ),
        migrations.AddField(
            model_name='products',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categories'),
        ),
        migrations.CreateModel(
            name='Salesproduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('time', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('discount', models.CharField(max_length=20)),
                ('Holat', models.CharField(max_length=30)),
                ('total_weight', models.CharField(max_length=40)),
                ('photo1', models.ImageField(blank=True, null=True, upload_to='sales')),
                ('photo2', models.ImageField(blank=True, null=True, upload_to='sales')),
                ('photo3', models.ImageField(blank=True, null=True, upload_to='sales')),
                ('photo4', models.ImageField(blank=True, null=True, upload_to='sales')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
            ],
        ),
    ]
