# Generated by Django 5.0.2 on 2024-02-21 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_blogs_categories_rename_photo_products_photo1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='foiz',
            field=models.CharField(blank=True, max_length=23, null=True),
        ),
        migrations.AddField(
            model_name='products',
            name='stasus',
            field=models.CharField(blank=True, max_length=22, null=True),
        ),
    ]
