# Generated by Django 5.0.2 on 2024-02-22 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_products_foiz_products_stasus'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='aksiy_price',
            field=models.DecimalField(decimal_places=0, default='0', max_digits=10, verbose_name=' Aksiya Narxni belgilang'),
        ),
        migrations.AddField(
            model_name='products',
            name='aksiya',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
